    version: '2'
    services:
      db_central:
        image: postgres
      db_local_1:
        image: postgres
      db_local_2:
        image: postgres
      web_1:
        build: .
        command: bundle exec rails s -b '0.0.0.0'
        volumes:
          - .:/rbd_warehouse_1
        ports:
          - "4000:3000"
        depends_on:
          # - db_central
          - db_local_1
        links:
          # - db_central
          - db_local_1:db
      web_2:
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
          - .:/rbd_warehouse_2
        ports:
          - "4001:3000"
        depends_on:
          # - db_central
          - db_local_2
        links:
          # - db_central
          - db_local_2:db
