version: '2'
volumes:
  db_central-data:
  db_local_1-data:
  db_local_2-data:
services:
  db_central:
    image: postgres
    volumes:
      - db_central-data:/var/lib/postgresql/data
  db_local_1:
    image: postgres
    volumes:
      - db_local_1-data:/var/lib/postgresql/data
  db_local_1_pgpool:
    build:
      context: .
      dockerfile: Dockerfile.pgpool
    external_links:
      - db_local_1:db_local
      - db_central
  db_local_2:
    image: postgres
    volumes:
      - db_local_2-data:/var/lib/postgresql/data
  db_local_2_pgpool:
    build:
      context: .
      dockerfile: Dockerfile.pgpool
    external_links:
      - db_local_2:db_local
      - db_central
  web_1:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    environment:
      - PK_PREFIX=web1
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - db_central
      - db_local_1_pgpool
    links:
      - db_local_1_pgpool:db
    # tty: true
    # stdin_open: true

  web_2:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    environment:
      - PK_PREFIX=web2
    volumes:
      - .:/code
    ports:
      - "3001:3000"
    depends_on:
      - db_central
      - db_local_2_pgpool
    links:
      - db_local_2_pgpool:db
    # tty: true
    # stdin_open: true
